# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  den.url = "github:vic/den";
  flake-file.url = "github:vic/flake-file";
  flake-parts = {
    inputs.nixpkgs-lib.follows = "nixpkgs";
    url = "github:hercules-ci/flake-parts";
  };
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager";
  };
  import-tree.url = "github:vic/import-tree";
  nixpkgs.url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
}
